### ISSUE TITLE
Community Help Service is down'ish

### ISSUE THREAD

**Issue by almereyda** [grnet/synnefo#373]
https://ask.synnefo.org/ shows 502.

**Comment by Erethon** [comment]
We're in the process of deprecating that service. Thank you for the reminder to remove the dead links!

**Comment by Erethon** [comment]
Forgot to mention, that the goto place for getting help with Synnefo, is our public mailing list synnefo@googlegroups.com

**Comment by almereyda** [comment]
Thanks to report. Was it underused and overruled by the Google list, or even synnefo going to be deprecated?
Just discovered it and consider it a nice interface for the likes for @ecobytes.

**Comment by Erethon** [comment]
> Thanks to report. Was it underused and overruled by the Google list

It was completely underused as you said, most people prefer to use the mailing list.

> or even synnefo going to be deprecated?

Synnefo isn't going to be deprecated, that's for sure :). GRNET is currently using Synnefo to provide over four thousand VMs to the Greek and European academic community through [~okeanos](https://okeanos.grnet.gr/home/) and [~okeanos-global](https://okeanos-global.grnet.gr/home/) respectively.

We've got a lot of features planned ahead :)

> Just discovered it and consider it a nice interface for the likes for @ecobytes.

Took a quick look at @ecobytes, I guess Synnefo can fill some of your needs.

**Comment by almereyda** [comment]
> We've got a lot of features planned ahead :)

The interest from our side would be to have it running on Debian 8 first. Then we could easily approach a federation of community-supported infrastructure. Especially the virtual grouping of resources into projects makes sense for us, as it would allow for community-driven maintenance of pooled resources for protected Commons like @transformap which don't have a central legal entity.

Next step: Containers ;) (Mesos, Rancher, Weave, etc.)

cc @vchryssos @jbonicioli

**Comment by Erethon** [comment]
> Do you have this roadmap public somewhere?

Not yet, but will be announced during the next month, targeting the next two or
three years. We're in the process of closing our old development cycle and
starting a new one, and that includes some bureaucracy.

> Because we're really interested in delivering our Ecobytes Use Case, but
> only after implementation.

We'll sure take your suggestions into consideration, feel free to send them to us.

> The interest from our side would be to have it running on the latest Debian
> release, namely Jessie/8, first. 

This is a work in progress actually since we'll soon move our datacenters to
Jessie ourselves.

> Next step: Containers ;) (Mesos, Rancher, Weave, etc.)
> One could also skip the Debian 8 part and think about running Synnefo
> completely containerized, too.

We're moving our internal CI infrastructure to containers, and we're
considering technologies such as Kubernetes, Mesos, etc. for our production in
the future.

> This may be a bit of hard work, due to the complexity of OpenStack and your
> integrations, though.

Note that, Synnefo doesn't actually use any OpenStack components, it just
implements OpenStack APIs.
